{
 "title": "Metrics & logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Process Cpu Seconde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Max  Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/containers/loki-7b46bd6cf6-rjvpd_monitoring_loki-460f931696ebee84258d6c50a80c8b1062e90ddb313465113bdea353300fb2cd.log\"}"
    }
   ]
  }
 ]
}